# This file exposes the package version.
# It is auto-generated by setuptools_scm during the build process.
try:
    from ._version import __version__
except ImportError:
    __version__ = "0.0.0-dev"

from nansen.io.gpx import read_gpx_track
